### ISSUE TITLE
line 407 in cls_hrnet.py,how to set num_inchannels

### ISSUE THREAD

**Issue by ChaosZX** [HRNet/HRNet-Image-Classification#1]
The num_inchannels can't be found at config.py and other python-files

**Comment by wondervictor** [comment]
You can find it in [lib/config/model.py](https://github.com/HRNet/HRNet-Image-Classification/blob/master/lib/config/models.py). Configurations for models are in this file.

**Comment by wondervictor** [comment]
@ChaosZX ， `num_inchannels`  in https://github.com/HRNet/HRNet-Image-Classification/blob/00a263341a22ebe72a318e092baddd336d2392af/lib/models/cls_hrnet.py#L406 is a function parameter.

**Comment by ChaosZX** [comment]
@wondervictor  Thks for the quick reply. That's what i confused, _make_stage parameter should be set default value in ClassHighResolutionNet function  __init__,but the num_inchannels can't be found in  this function.

**Comment by wondervictor** [comment]
Hi, you can see this： https://github.com/HRNet/HRNet-Image-Classification/blob/00a263341a22ebe72a318e092baddd336d2392af/lib/models/cls_hrnet.py#L275, we pass the `num_channels` as `num_inchannels` to  `make_stage` function.

**Comment by ChaosZX** [comment]
@wondervictor I got it thank you  very much!
