### ISSUE TITLE
Could someone help to put the pretrained models in google drive?

### ISSUE THREAD

**Issue by MaitaYuki** [HRNet/HRNet-Image-Classification#30]
I am interested in the following models:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"

I am not able to download them from baidu. I wonder if someone can help to put them in google drive. 
Many thanks.

**Comment by PkuRainBow** [comment]
@MaitaYuki Please download them from https://github.com/HRNet/HRNet-Image-Classification/releases/tag/PretrainedWeights
