### ISSUE TITLE
when will you release the pretrain models? the onedrive links are all broken?

### ISSUE THREAD

**Issue by nemonameless** [HRNet/HRNet-Image-Classification#5]
when will you release the pretrain models? the onedrive links are all broken?
or can you release the download links in google drive or  BaiduYun? thanks

**Comment by sunke123** [comment]
Hi @nemonameless ,
I can download the models through these links successfully.
I will try to put them on google drive.

**Comment by MaitaYuki** [comment]
@sunke123,
I am not able to download the models from baidu. I am able to download from google drive. I wonder if you can put them in google drive as you mentioned. Thanks for your help.
